version: "2"
services:
  opentelemetry2:
    image: ${DOCKER_REGISTRY-}opentelemetry2
    build:
      context: .
      dockerfile: opentelemetry2/Dockerfile
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14269:14269
      - 14250:14250
      - 9411:9411
      - 4317:4317
      - 4318:4318
